// Bundled into the native ModuleLoader factory by build.mjs. Uses host React.
function createApplication(React,logic){
 const h=React.createElement,{useState,useEffect,useRef}=React;
 const {analyse,makeAnalysisPrompt,FIELDS}=logic;
 const tabs=[['overview','总览'],['collect','平台与采集'],['library','资料库'],['analysis','结果分析'],['reports','周报与行动'],['settings','品牌与数据源']];
 const labels={untested:'待测试',ready:'已验收',queued:'待运行',running:'执行中',paused:'已暂停',needs_login:'需要登录',blocked:'需要人工处理',failed:'失败',needs_review:'待核对证据',completed:'已完成'};
 const call=async(path,data={})=>{const r=await fetch('/api/seo-geo-v3/'+path,{method:'POST',headers:{'Content-Type':'application/json','X-DSH-Monitor':'1'},body:JSON.stringify(data)});const value=await r.json();if(!r.ok)throw Error(value.error||'操作失败');return value;};
 const button=(text,action,primary=false,disabled=false)=>h('button',{className:'sg-btn'+(primary?' primary':''),onClick:action,disabled,type:'button'},text);
 const field=(label,child)=>h('label',{className:'sg-field'},h('span',null,label),child);
 const select=(value,onChange,options,label)=>h('select',{'aria-label':label,value,onChange:e=>onChange(e.target.value)},options.map(([id,name])=>h('option',{key:id,value:id},name)));
 const input=(value,onChange,label,type='text')=>h('input',{'aria-label':label,type,value,onChange:e=>onChange(e.target.value)});
 const table=(headers,rows)=>h('div',{className:'sg-scroll'},h('table',{className:'sg-table'},h('thead',null,h('tr',null,headers.map(x=>h('th',{key:x},x)))),h('tbody',null,rows.map((r,i)=>h('tr',{key:i},r.map((x,j)=>h('td',{key:j},x)))))));
 const empty=text=>h('div',{className:'sg-empty'},text);
 const panel=(title,...content)=>h('section',{className:'sg-panel'},h('h2',null,title),...content);
 function download(name,text,type='text/plain;charset=utf-8'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function binaryDownload(name,base64){const bytes=Uint8Array.from(atob(base64),c=>c.charCodeAt(0));download(name,bytes,'application/octet-stream');}
 function textFromSession(session){const events=session.eventSource.getSnapshot().entries.map(e=>e.event||e);const messages=events.filter(e=>e.type==='assistant/message').map(e=>{const d=e.data||{};const c=d.content||d.message?.content;return typeof c==='string'?c:Array.isArray(c)?c.filter(x=>x.type==='text').map(x=>x.text).join(''):d.text||'';});const failure=events.filter(e=>e.type==='assistant/attempt').flatMap(e=>e.data?.stream||[]).find(e=>e.chunk?.type==='finish'&&e.chunk.reason?.kind==='error')?.chunk.reason.failure?.message;return {text:messages.join('\n\n'),ended:events.some(e=>e.type==='turn/end'),failure};}
 async function runNative(runtime,prompt,onProgress,signal,selection){
  if(!runtime?.sessions||!runtime?.workbenches)throw Error('请在 DSH 桌面工作台内运行 AI 分析或采集；当前预览支持资料导入与统计。');
  const id=await runtime.workbenches.create({workbenchId:'seo-geo',background:true});const session=runtime.sessions.binding(id)?.session;if(!session)throw Error('DSH 会话尚未连接');
  await session.open();
  if(selection?.provider)await call('configure-session',{sessionId:id,...selection});
  onProgress({id,text:'已建立 DSH 执行会话，等待模型回复…'});
  const response=await session.prompt([{type:'text',text:prompt}],'queue');if(!response.ok)throw Error(response.error?.message||'发送失败');
  const start=Date.now();while(Date.now()-start<600000){if(signal?.aborted){await session.cancel?.();throw Error('已停止等待；任务可在 DSH 会话中查看');}await session.resync();const result=textFromSession(session);const snap=session.getSnapshot();if(result.failure||snap.lastAgentError)throw Error(result.failure||snap.lastAgentError.message);onProgress({id,text:result.text||'DSH 正在处理，请稍候…'});if(result.ended){if(result.text)return {...result,id};throw Error('DSH 本轮已结束，但没有可保存的回答。请查看原生会话。');}await new Promise(r=>setTimeout(r,1800));}
  throw Error('本次等待超过 10 分钟，可打开 DSH 原生会话检查结果');
 }
 function App({runtime}){
  const [state,setState]=useState(null),[view,setView]=useState('overview'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  const [chosen,setChosen]=useState(['deepseek','doubao','kimi','chatgpt']),[name,setName]=useState(''),[url,setUrl]=useState(''),[showAdd,setShowAdd]=useState(false);
  const [question,setQuestion]=useState('DSH Desktop 是什么？它适合哪些用户？'),[group,setGroup]=useState('品牌'),[repeat,setRepeat]=useState('1'),[mode,setMode]=useState('联网搜索');
  const [previews,setPreviews]=useState([]),[paste,setPaste]=useState(''),[filter,setFilter]=useState({source:'imported'}),[analysisTab,setAnalysisTab]=useState('brand'),[query,setQuery]=useState('综合分析这些资料，列出有证据支持的发现与下周行动。');
  const [progress,setProgress]=useState(null),[brand,setBrand]=useState(null),[images,setImages]=useState({}),[lastEvidence,setLastEvidence]=useState([]),[modelKey,setModelKey]=useState(()=>{try{return localStorage.getItem('dsh-seo-geo-execution-model')||'';}catch{return '';}}),[catalog,setCatalog]=useState(null),[chromeInfo,setChromeInfo]=useState(null);
  const abort=useRef(null),lock=useRef(false),mounted=useRef(true),currentTask=useRef(null);
  let selection=null;try{selection=modelKey?JSON.parse(modelKey):null;}catch{}
  useEffect(()=>{try{localStorage.setItem('dsh-seo-geo-execution-model',modelKey);}catch{}},[modelKey]);
  useEffect(()=>{if(runtime)call('configure-session',{catalog:true}).then(setCatalog).catch(e=>setMessage(e.message));},[]);
  const executionSettings=()=>field('执行模型',select(modelKey,setModelKey,[['',catalog?.default?`DSH 默认：${catalog.default.provider} / ${catalog.default.model}`:'使用 DSH 当前模型'],...(catalog?.groups||[]).flatMap(g=>g.models.map(m=>[JSON.stringify({provider:g.id,model:m.id}),`${g.name} / ${m.name}`]))],'执行模型'));
  const refresh=async()=>{const s=await call('state');if(mounted.current){setState(s);setBrand(b=>b||s.brand);}return s;};
  useEffect(()=>{mounted.current=true;runtime?.workbenches?.coverConversation('seo-geo',true);refresh().catch(e=>setMessage(e.message));return()=>{mounted.current=false;runtime?.workbenches?.coverConversation('seo-geo',false);};},[]);
  const perform=async(fn)=>{if(lock.current)return;lock.current=true;setBusy(true);setMessage('');try{await fn();}catch(e){setMessage(e.message);}finally{lock.current=false;if(mounted.current)setBusy(false);}};
  const act=async a=>{await call('action',a);return refresh();};
  const go=v=>{setView(v);setMessage('');};
  const add=()=>perform(async()=>{await act({type:'platform.add',name,url});setName('');setUrl('');setShowAdd(false);setMessage('网站已添加，运行一题测试后可验收采集能力。');});
  async function files(files){await perform(async()=>{const results=[],errors=[];for(const file of files){try{if(file.size>8*1024*1024)throw Error('超过 8 MB');const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=16384)binary+=String.fromCharCode(...bytes.subarray(i,i+16384));const payload={name:file.name,base64:btoa(binary)};const p=await call('preview',payload);results.push({...p,payload});}catch(e){errors.push(file.name+'：'+e.message);}}setPreviews(v=>[...v,...results]);setMessage(errors.join('\n')||`已解析 ${results.length} 个文件，请预览后导入。`);});}
  const editPreview=(id,changes)=>setPreviews(ps=>ps.map(p=>p.id===id?{...p,...changes}:p));
  async function executeTask(task){
   currentTask.current=task.id;
   abort.current=new AbortController();
   try{await runNative(runtime,`请使用 seo_geo_browser 工具执行 GEO 采样任务 ${task.id}。固定问题：${task.question}。目标网站：${task.url}。目标模式：${task.mode}。先 begin，然后根据实际页面快照点击新建对话、核对模式、fill 原题、发送。不得直接回答这个问题或调用其他模型代替网页结果。只能用这个工具操作浏览器。遇到登录/验证码立即 fail needs_login/blocked，不得尝试破解。完整回答后 capture，指定正确的回答区域及正式引用链接区域 selector，记录实际模式与页面模型。无法确认完成时 fail，不伪造成功。60 步/10 分钟内完成或说明失败。`,setProgress,abort.current.signal,selection);}finally{
   const next=await refresh();const actual=next.tasks.find(t=>t.id===task.id);if(actual&&['queued','running'].includes(actual.status))await act({type:'task.pause',id:task.id});currentTask.current=null;}
  }
  async function startQueue(){await perform(async()=>{const queue=state.tasks.filter(t=>t.status==='queued');if(!queue.length)throw Error('请先创建采样任务');for(const t of queue){await executeTask(t);if(abort.current?.signal.aborted)break;}setMessage('本批执行结束，请在结果分析中核对已保存的样本；未完成项保留状态。');});}
  const stop=()=>{abort.current?.abort();if(currentTask.current)call('action',{type:'task.pause',id:currentTask.current}).then(refresh).catch(e=>setMessage(e.message));setMessage('已请求停止；采集任务将保留，可继续或重试。');};
  if(!state)return h('div',{className:'sg-app'},h('main',{className:'sg-main'},h('h1',null,'正在读取工作台'),h('p',null,message||'加载平台、资料和任务…')));
  const a=analyse(state,filter),active=state.imports.filter(x=>!x.revoked),rate=(n,d)=>d?`${(100*n/d).toFixed(1)}%`:'暂无数据';
  const updateFilter=(key,value)=>setFilter(f=>({...f,[key]:value}));
  const showEvidence=ids=>{setLastEvidence(ids);setAnalysisTab('evidence');setView('analysis');};
  const evidenceButton=ids=>button(`查看 ${new Set(ids).size} 条证据`,()=>showEvidence(ids),false,!ids.length);
  const stats=h('div',{className:'sg-stats'},[['有效 GEO 样本',a.geo.length,'当前筛选口径'],['品牌出现率',rate(a.mentions,a.geo.length),`${a.mentions} / ${a.geo.length} 条`],['官网引用率',rate(a.cited,a.geo.length),`${a.cited} / ${a.geo.length} 条`],['可用资料批次',active.length,'原件可追溯']].map(([label,value,note])=>h('div',{className:'sg-stat',key:label},h('small',null,label),h('b',null,value),h('small',null,note))));
  const filters=h('div',{className:'sg-toolbar'},field('数据来源',select(filter.source||'',v=>updateFilter('source',v),[['imported','用户导入'],['official_web','官方网页采集'],['','全部来源（分组展示）']],'数据来源')),field('平台',select(filter.platform||'',v=>updateFilter('platform',v),[['','全部平台'],...[...new Set(state.records.map(r=>r.platform).filter(Boolean))].map(x=>[x,x])],'筛选平台')),field('题型',select(filter.group||'',v=>updateFilter('group',v),[['','全部题型'],...[...new Set(state.records.map(r=>r.group))].map(x=>[x,x])],'筛选题型')),field('资料批次',select(filter.batchId||'',v=>updateFilter('batchId',v),[['','全部批次'],...active.map(x=>[x.id,x.name])],'资料批次')),field('开始日期',input(filter.from||'',v=>updateFilter('from',v),'开始日期','date')),field('结束日期',input(filter.to||'',v=>updateFilter('to',v),'结束日期','date')));
  const actions=a.actions.length?a.actions.map((x,i)=>h('div',{className:'sg-answer',key:x.title},h('h3',null,`${i+1}. ${x.title}`),h('p',null,x.detail),evidenceButton(x.ids))):empty('当前数据尚不足以生成规则行动项。可上传资料，或让 DSH 深入分析。');
  let content;
  if(view==='overview')content=h(React.Fragment,null,h('div',{className:'sg-toolbar'},button('选择平台采集',()=>go('collect'),true),button('添加 AI 网站',()=>{go('collect');setShowAdd(true);}),button('上传资料分析',()=>go('library'))),h('p',{className:'sg-note'},'从真实回答和已有资料开始。首页统计默认仅看导入样本，可在结果分析中切换来源、题型和时间。'),stats,panel('下一步行动',actions),panel('最近采样任务',state.tasks.length?table(['平台','问题','状态'],state.tasks.slice(-5).reverse().map(t=>[t.platformName||t.platformId,t.question||t.questionId,labels[t.status]||t.status])):empty('选择预设平台或添加新网站，开始第一轮采样。')));
  if(view==='collect')content=h(React.Fragment,null,panel('我的 Chrome',h('p',null,'默认使用你日常的 Google Chrome，复用已登录的 AI 网站。首次自动采集需要连接本地扩展。'),h('div',{className:'sg-toolbar'},button('检查连接 / 获取连接码',()=>perform(async()=>setChromeInfo(await call('chrome-connection'))),false,busy),chromeInfo&&button('断开 Chrome',()=>perform(async()=>{await call('chrome-disconnect');setChromeInfo(null);setMessage('Chrome 已断开。');}),false,busy)),chromeInfo&&h('div',null,h('p',null,chromeInfo.connected?'已连接：自动采集将在这个 Chrome 账号的新标签页中执行。':'尚未连接：在 Chrome 扩展管理页加载下方目录，然后在扩展中粘贴连接码。'),field('扩展目录',h('input',{readOnly:true,value:chromeInfo.extensionPath})),field('Chrome 连接码',h('textarea',{'aria-label':'Chrome 连接码',readOnly:true,value:chromeInfo.connection})),h('small',null,'首次：chrome://extensions → 开发者模式 → 加载已解压的扩展程序。连接码仅给本地扩展，DSH 重启后重新获取。'))),h('div',{className:'sg-toolbar'},button(showAdd?'收起添加':'添加 AI 网站',()=>setShowAdd(!showAdd),true),h('span',{className:'sg-muted'},'自由选择平台；新增网站先做一题验证。')),
   showAdd&&panel('添加 AI 网站',h('div',{className:'sg-toolbar'},field('网站名称',input(name,setName,'网站名称')),field('HTTPS 地址',input(url,setUrl,'HTTPS 地址')),button('保存网站',add,true,busy))),
   h('div',{className:'sg-grid'},state.platforms.map(p=>h('article',{className:'sg-platform',key:p.id},h('label',null,h('input',{type:'checkbox',checked:chosen.includes(p.id)&&p.enabled,disabled:!p.enabled,onChange:()=>setChosen(v=>v.includes(p.id)?v.filter(x=>x!==p.id):[...v,p.id])}),p.name),h('small',null,new URL(p.url).hostname),h('span',{className:'sg-pill'},p.enabled?(labels[p.status]||'待测试'):'已停用'),h('div',{className:'sg-toolbar'},button('打开 / 登录',()=>perform(async()=>{const r=await call('browser',{id:p.id});setMessage(r.message);}),false,busy||!p.enabled),button(p.enabled?'停用':'启用',()=>perform(()=>act({type:'platform.toggle',id:p.id})),false,busy))))),
   panel('建立采样任务',field('固定问题',h('textarea',{'aria-label':'固定问题',value:question,onChange:e=>setQuestion(e.target.value)})),h('div',{className:'sg-toolbar'},field('题型',select(group,setGroup,['品牌','品类','场景','对比','信任','安装','未分类'].map(x=>[x,x]),'题型')),field('采样模式',select(mode,setMode,[['联网搜索','联网搜索'],['普通问答','普通问答'],['unknown','不指定，记录实际模式']],'采样模式')),field('重复次数',select(repeat,setRepeat,[1,2,3,4,5].map(x=>[String(x),String(x)]),'重复次数')),button('加入采样队列',()=>perform(async()=>{await act({type:'tasks.add',platformIds:chosen,question,group,mode,repeat:Number(repeat)});setMessage('已加入队列，点击开始采集后由 DSH 执行。');}),true,busy))),
   panel('执行队列',executionSettings(),h('p',{className:'sg-note'},'DSH 将调用浏览器工具，操作已连接的 Chrome 账号。复用该账号的登录状态，登录过期时需用户处理。每条采集完成后核对证据，才纳入正式指标。'),h('div',{className:'sg-toolbar'},button('开始采集',startQueue,true,busy),button('停止执行',stop,false,!busy),button('刷新状态',()=>perform(refresh),false,busy)),state.tasks.length?table(['平台 / 轮次','问题','状态','操作'],state.tasks.slice().reverse().map(t=>[`${t.platformName||t.platformId} / ${t.repeatIndex}`,t.question||t.questionId,h('div',null,labels[t.status]||t.status,t.error&&h('p',null,t.error)),h('div',{className:'sg-toolbar'},!['completed','needs_review'].includes(t.status)&&button(t.status==='paused'||['failed','blocked','needs_login'].includes(t.status)?'重试':'暂停',()=>perform(()=>act({type:t.status==='queued'||t.status==='running'?'task.pause':'task.retry',id:t.id})),false,busy),t.sampleId&&button('查看结果',()=>{setFilter({source:'official_web'});showEvidence([t.sampleId]);}))])):empty('暂无任务')));
  if(view==='library')content=h(React.Fragment,null,h('section',{className:'sg-drop',onDragOver:e=>e.preventDefault(),onDrop:e=>{e.preventDefault();files([...e.dataTransfer.files]);}},h('h2',null,'上传资料分析'),h('p',null,'拖拽多个文件到这里，或选择文件。Excel / CSV / TSV / JSON / TXT / Markdown，单个最多 8 MB。'),h('input',{type:'file',multiple:true,accept:'.xlsx,.xls,.csv,.tsv,.json,.txt,.md','aria-label':'选择资料文件',disabled:busy,onChange:e=>{files([...e.target.files]);e.target.value='';}})),
   panel('粘贴已有资料',field('资料正文',h('textarea',{'aria-label':'资料正文',value:paste,onChange:e=>setPaste(e.target.value),placeholder:'粘贴 AI 回答、研究笔记或报告片段'})),h('div',{className:'sg-toolbar'},button('解析文本',()=>perform(async()=>{const p=await call('preview',{name:'粘贴资料.txt',text:paste});setPreviews(v=>[...v,p]);setPaste('');}),true,busy||!paste.trim()))),
   ...previews.map(p=>panel(`预览：${p.name}`,h('p',null,`${p.totalRows} 条，预览前 ${p.rows.length} 条。导入日期不会替代采样日期。`),h('div',{className:'sg-toolbar'},field('资料类型',select(p.kind,v=>editPreview(p.id,{kind:v}),[['geo','AI 逐题回答'],['seo','SEO 数据'],['traffic','访问 / 下载数据'],['research','背景研究资料']],'资料类型')),field('来源说明',input(p.sourceLabel||'',v=>editPreview(p.id,{sourceLabel:v}),'来源说明')),p.sheets?.length>1&&field('工作表',select(p.sheet,v=>perform(async()=>{const next=await call('preview',{...p.payload,sheet:v});setPreviews(ps=>ps.map(x=>x.id===p.id?{...next,payload:p.payload}:x));}),p.sheets.map(x=>[x,x]),'工作表'))),
    p.kind!=='research'&&h('div',{className:'sg-grid'},(p.kind==='geo'?['question','answer','platform','date','citations','sourceUrl','group','mode','locale','region']:p.kind==='seo'?['date','keyword','page','clicks','impressions','position']:['date','channel','page','visits','downloads']).map(k=>field(FIELDS[k].find(x=>/[\u4e00-\u9fff]/.test(x))||k,select(p.mapping[k]||'',v=>editPreview(p.id,{mapping:{...p.mapping,[k]:v}}),[['','未提供'],...Object.keys(p.rows[0]||{}).map(x=>[x,x])],`匹配 ${k}`)))),
    h('pre',{className:'sg-pre'},JSON.stringify(p.rows,null,2)),h('div',{className:'sg-toolbar'},button('确认导入',()=>perform(async()=>{const r=await call('commit',{id:p.id,mapping:p.mapping,kind:p.kind,sourceLabel:p.sourceLabel});await refresh();setPreviews(ps=>ps.filter(x=>x.id!==p.id));setMessage(`已导入 ${r.batch.count} 条，跳过重复 ${r.batch.duplicates} 条。`);}),true,busy),button('取消预览',()=>setPreviews(ps=>ps.filter(x=>x.id!==p.id)),false,busy)))),
   panel('已导入资料',state.imports.length?table(['文件 / 来源','类型','记录','状态','操作'],state.imports.slice().reverse().map(b=>[h('div',null,b.name,h('small',{className:'sg-muted'},' '+b.sourceLabel)),b.kind,b.count,b.revoked?'已撤销':'可分析',h('div',{className:'sg-toolbar'},button('下载原件',()=>perform(async()=>{const r=await call('original',{id:b.id});binaryDownload(r.name,r.base64);})),!b.revoked&&button('分析此资料',()=>{setFilter({source:'imported',batchId:b.id});go('analysis');}),!b.revoked&&button('撤销导入',()=>perform(()=>act({type:'import.revoke',id:b.id})),false,busy))])):empty('尚未导入资料。先上传文件，或粘贴已有内容。')));
  if(view==='analysis')content=h(React.Fragment,null,filters,h('div',{className:'sg-tabs'},[['brand','品牌可见性'],['competitor','竞品对比'],['citations','引用来源'],['seo','SEO 与流量'],['trends','趋势'],['evidence','回答与证据'],['ai','DSH 深入分析']].map(([id,title])=>h('button',{key:id,className:'sg-btn','aria-pressed':analysisTab===id,onClick:()=>{setAnalysisTab(id);if(id==='evidence')setLastEvidence([]);}},title))),
   analysisTab==='brand'&&h(React.Fragment,null,stats,h('p',{className:'sg-note'},'品牌出现采用文本匹配；主体准确、推荐理由和同名混淆请结合原文或 DSH 深入分析。不同题型与来源分别展示。'),a.byPlatform.length?panel('按平台、题型与来源',table(['分组','有效样本','品牌出现','证据'],a.byPlatform.map(p=>[p.name,p.total,`${p.mentioned} / ${p.total}`,evidenceButton(p.ids)]))):empty('暂无完整 GEO 样本。逐题数据需包含问题、回答、平台及采样日期。')),
   analysisTab==='competitor'&&panel('竞品在回答中的出现',h('p',{className:'sg-muted'},'同一条回答内重复出现只计一次；出现次数不等于推荐次数。'),table(['产品','出现样本','证据'],a.competitors.map(p=>[p.name,p.total,evidenceButton(p.ids)]))),
   analysisTab==='citations'&&panel('正式引用域名',a.domains.length?table(['域名','引用样本数','证据'],a.domains.map(p=>[p.name,p.total,evidenceButton(p.ids)])):empty('当前引用字段为空或没有有效链接，不能据此断言平台没有引用。')),
   analysisTab==='seo'&&h(React.Fragment,null,panel('SEO 数据',a.seo.length?table(['日期','关键词 / 页面','曝光','点击','CTR','平均排名'],a.seo.map(r=>[r.date.slice(0,10)||'未知',r.keyword||r.page,r.impressions??'未知',r.clicks??'未知',r.clicks!==null&&r.impressions?rate(r.clicks,r.impressions):'未知',r.position??'未知'])):empty('导入搜索词、点击、曝光和页面数据后分析。')),panel('访问与下载',a.traffic.length?table(['日期','渠道 / 页面','访问','下载'],a.traffic.map(r=>[r.date.slice(0,10)||'未知',r.channel||r.page,r.visits??'未知',r.downloads??'未知'])):empty('导入 Cloudflare 或下载记录后展示。未取得追踪证据时不做因果归因。')),panel('待复核机会',actions)),
   analysisTab==='trends'&&panel('同条件每日样本',h('p',{className:'sg-muted'},'按平台、来源、原题、搜索模式、语言、地区和日期分组；未知环境只能作描述性参考。'),a.trends.length?table(['条件与日期','有效样本','品牌出现率','证据'],a.trends.map(t=>[t.name,t.total,rate(t.mentioned,t.total),evidenceButton(t.ids)])):empty('积累多个日期的采样后，可按相同条件比较。')),
   analysisTab==='evidence'&&panel('原始资料与回答',...(a.selected.filter(r=>!lastEvidence.length||lastEvidence.includes(r.id)).length?a.selected.filter(r=>!lastEvidence.length||lastEvidence.includes(r.id)).map(r=>h('details',{key:r.id,className:'sg-answer',open:lastEvidence.includes(r.id)},h('summary',null,`${r.platform||r.kind} | ${r.question||r.location} | ${r.date?.slice(0,10)||'日期未知'}`),h('p',{className:'sg-muted'},`[${r.id}] ${r.location} · ${r.source==='official_web'?'官方网页':'用户导入'}`),h('pre',{className:'sg-pre'},r.answer||JSON.stringify(r.raw,null,2)),r.issues?.length>0&&h('p',null,r.issues.join('；')),r.sourceUrl&&h('a',{className:'sg-link',href:r.sourceUrl,target:'_blank',rel:'noreferrer'},'打开原页面'),...r.citations.map(u=>h('p',{key:u},h('a',{href:u,target:'_blank',rel:'noreferrer',className:'sg-link'},u))),r.source==='official_web'&&h('div',{className:'sg-toolbar'},button('查看截图',()=>perform(async()=>{const img=await call('screenshot',{id:r.id});setImages(v=>({...v,[r.id]:'data:image/png;base64,'+img.base64}));})),!r.eligible&&button('已核对完整性与引用',()=>perform(()=>act({type:'sample.verify',id:r.id})),true,busy)),images[r.id]&&h('img',{src:images[r.id],alt:'官方网页采样证据'}))):[empty('当前筛选没有资料。')])),
   analysisTab==='ai'&&panel('向 DSH 提问',h('p',null,`将分析当前筛选的 ${a.selected.length} 条记录，使用下方选择的 DSH 模型；结果保留证据编号。`),executionSettings(),field('分析问题',h('textarea',{'aria-label':'分析问题',value:query,onChange:e=>setQuery(e.target.value)})),h('div',{className:'sg-toolbar'},button('开始分析',()=>perform(async()=>{abort.current=new AbortController();currentTask.current=null;const result=await runNative(runtime,makeAnalysisPrompt(state,a.selected,query),setProgress,abort.current.signal,selection);await act({type:'report.save',text:result.text,question:query,recordIds:a.selected.map(r=>r.id),sessionId:result.id});setMessage('分析已完成，并保存到周报与行动。');}),true,busy||!a.selected.length),button('停止分析',stop,false,!busy))));
  if(view==='reports')content=h(React.Fragment,null,panel('当前筛选的行动建议',actions,h('div',{className:'sg-toolbar'},button('导出监测报告',()=>perform(async()=>{const r=await call('report',filter);download('SEO-GEO监测报告.md',r.text);setMessage('报告已保存到项目 outputs/monitor-v3，并下载 Markdown。');}),true,busy))),panel('DSH 分析记录',state.reports.length?state.reports.slice().reverse().map(r=>h('details',{className:'sg-answer',key:r.id},h('summary',null,r.createdAt.slice(0,16)+' '+r.question),h('pre',{className:'sg-pre'},r.text),button('导出分析',()=>download('DSH分析-'+r.id+'.md',r.text)),button('查看原始证据',()=>{setFilter({});showEvidence(r.recordIds);} ))):empty('在结果分析中运行 DSH 深入分析，完成结果会保存在这里。')));
  if(view==='settings')content=h(React.Fragment,null,panel('监测品牌',h('div',{className:'sg-grid'},field('品牌名称',input(brand.name,v=>setBrand(b=>({...b,name:v})),'品牌名称')),field('官网域名',input(brand.domain,v=>setBrand(b=>({...b,domain:v})),'官网域名')),field('品牌别名（逗号分隔）',input(brand.aliases.join(','),v=>setBrand(b=>({...b,aliases:v.split(/[,，]/).map(x=>x.trim())})),'品牌别名')),field('竞品（逗号分隔）',input(brand.competitors.join(','),v=>setBrand(b=>({...b,competitors:v.split(/[,，]/).map(x=>x.trim()).filter(Boolean)})),'竞品'))),h('div',{className:'sg-toolbar'},button('保存品牌设置',()=>perform(()=>act({type:'brand.save',brand})),true,busy))),panel('数据源与执行环境',table(['入口','状态与说明'],[['用户上传','已接通文件解析、证据保存与分析'],['DSH 浏览器工具','默认你的 Chrome；本地扩展连接后复用该账号登录，按平台逐题验收'],['DSH 分析模型','复用 DSH 原生会话及当前模型配置'],['Cloudflare / GSC / Bing','支持导出文件导入，未接入自动同步'],['DataForSEO / Semrush','支持导出资料分析，在线接口未配置'],['PDF / Word / 截图 OCR','后续接入；当前不宣称支持'],['定时采集','当前手动启动批次，尚未启用定时调度']])));
  return h('div',{className:'sg-app'},h('aside',{className:'sg-side'},h('div',{className:'sg-brand'},h('b',null,'DSH Monitor'),h('small',null,'SEO / GEO 工作台')),h('nav',{className:'sg-nav','aria-label':'工作台导航'},tabs.map(([id,title])=>h('button',{key:id,'aria-current':view===id,onClick:()=>go(id)},title))),h('button',{className:'sg-exit',onClick:()=>runtime?.layout?.selectPanel(null)},'返回 DSH')),h('main',{className:'sg-main'},h('header',{className:'sg-head'},h('div',null,h('h1',null,tabs.find(t=>t[0]===view)[1]),h('p',null,'采集真实回答，汇集资料，用证据推动下一步。')),h('small',null,'v0.3.3')),message&&h('div',{className:'sg-alert',role:'status'},message),busy&&h('p',{className:'sg-note',role:'status'},'正在处理，请稍候…'),content,progress&&panel('DSH 执行记录',h('small',null,progress.id),h('pre',{className:'sg-pre'},progress.text))));
 }
 return {App,call};
}



